# Generated by Django 2.1 on 2019-06-26 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190626_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 26, 9, 6, 34, 643258)),
        ),
    ]
